### ISSUE TITLE
BUG: Help shows the executable name as logmaster instead of logviewer

### ISSUE THREAD

**Issue by stepanse** [tkmxqrdxddd/logviewer-systemd#1]
**Describe the bug**
When you execute ./logviewer --help, it shows the executable name as logmaster instead of logviewer

**To Reproduce**
1. execute logviewer --help
2. See that it says Usage: logmaster [options]

**Expected behavior**
Either the executable name is logmaster, or it displays logviewer as the correct application name

**Comment by tkmxqrdxddd** [comment]
Fixed
