### ISSUE TITLE
BUG: PKGBUILD tries to download non-existent tag of package

### ISSUE THREAD

**Issue by stepanse** [tkmxqrdxddd/logviewer-systemd#4]
**Describe the bug**
The PKGBUILD tries to download tag "v1.0.0", whereas the only tag that exists is "alpha"

**To Reproduce**
1. Try to install from PKGBUILD
2. See that makepkg can't find the URL stated in the PKGBUILD to download the source - GitHub returns 404 Not Found

**Expected behavior**
There is a valid URL to download from in the PKGBUILD so installation doesn't fail

**Comment by tkmxqrdxddd** [comment]
First try it, then make issue you dumb shit

**Comment by Jan64X** [comment]
Can confirm issue in fresh Arch Linux VM.
Could you please take a look at the issue head?

**Comment by stepanse** [comment]
Also can confirm - currently it tries to download the tag "valpha" instead of "alpha" - see gist for log
https://gist.github.com/stepanse/a3423e3c6553e7a281828ee83b610b16

**Comment by stepanse** [comment]
Also, I find it just a tiny bit rude to close my issue with the comment

> First try it, then make issue you dumb shit

and then try (but fail) to fix the *exact* bug I reported in this issue

(see [commit da361b2](https://github.com/tkmxqrdxddd/logviewer-systemd/commit/da361b22207b00a784b406a26b0c5e8dec49846c))

**Comment by tkmxqrdxddd** [comment]
Works on my machines @stepanse @Jan64X

**Comment by Jan64X** [comment]
Then your dev environment isn't setup correctly.
Please fix ASAP

**Comment by tkmxqrdxddd** [comment]
@Jan64X I'am unable to reproduce the issue
